### ISSUE TITLE
Registro de movimiento de Fuentes de financiamiento Traslado movimientos_crud

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/movimientos_crud#11]
Registro de movimiento de Fuentes de financiamiento Traslado movimientos_crud 5 horas - Carlos
- [x] Adecuación del modelo de datos para el registro de movimiento de traslado
- [x] incluir los cambios de ser necesario en el código del API

**Comment by CarlosGutierrezArdila** [comment]
![image](https://user-images.githubusercontent.com/32855979/60731900-50795c00-9f0e-11e9-9902-8e7b308f3cbd.png)
**Para el proceso de traslado:**
- En la tabla tipo de movimiento se incluye el movimiento de traslado (incluido en migraciones)
- En la tabla movimiento proceso externo se generan 2 registros uno para cada una de las fuentes involucradas, estos movimientos se referencian entre si por la columna movimiento proceso externo
- En el detalle de los movimientos se registra el valor de manera **POSITIVA** en la entrada (fuente destino) y de manera  **NEGATIVA** en la salida (fuente origen) 
Se trabaja con el mismo endpoint registrado para adicion y reduccion:
- **Endpoint:** movimiento_proceso_externo/registrar_movimiento
- **URL:** http://localhost:8085/v1/movimiento_proceso_externo/registrar_movimiento
- **Tipo de petición:** post
- **Parámetros:**
```json
{
	"TipoMovimiento": 3,
	"ProcesoExterno": 1,
        "MovimientoProcesoExterno": 2,
	"MovimientoDetalle": {
		"Valor": 700000.0,
		"FechaRegistro": "2019-07-01",
		"Descripcion": "Traslado de fuente de financiamiento X a fuente de financiamiento Y"
	}
}
```
la petición se debe hacer para ambas fuentes.

**Comment by Soulfilip-UD** [comment]
Excelente Documentación, por favor asociar PR una vez este resuelto el tema de la Socialización

**Comment by Soulfilip-UD** [comment]
Tarea completa y finalizada 
Proceeding to close Issue :space_invader:
