### ISSUE TITLE
Registro de movimiento de Fuentes de financiamiento Adición en movimientos_crud 5 horas  - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/movimientos_crud#12]
Registrar movimiento fuente de financiamiento 
- [x] Validar que el modelo de datos soporte el movimiento
- [x] Crear archivo de migración para que se cree el tipo de movimiento Adición
- [x] Desarrollar funcionalidad

**Comment by juancsr** [comment]
Aquí un ejemplo, con registros que el modelo es capaz de soportar los datos del movimiento. 
* Lo que está dentro del **cuadro azul es el modelo de movimientos**.
* Lo que está dentro del **cuadro verde es una representación del modelo de fuentes**, que para el modelo de movimientos este ultimo **se representa como un proceso externo**. 

![Prueba_movimiento_adcion_fuente_financiamiento](https://user-images.githubusercontent.com/19156525/60475846-eecf9e00-9c3e-11e9-9280-129cc314af17.png)

**Comment by juancsr** [comment]
Registro de movimiento adición:
* **Tipo de petición**: post
* **Parámetros**: 
```json
{
	"TipoMovimiento": 1,
	"ProcesoExterno": 1,
	"MovimientoDetalle": {
		"Valor": 300000.0,
		"FechaRegistro": "2019-07-01",
		"Descripcion": "Adición a fuente de financiamiento X"
	}
}
```
* **Endpoint**: movimiento_proceso_externo/registrar_movimiento
* **URL**: http://localhost:8085/v1/movimiento_proceso_externo/registrar_movimiento

![registro_movimiento_adicion](https://user-images.githubusercontent.com/19156525/60479320-0ca30000-9c4b-11e9-988e-f6f56f3e0bb3.png)

**Comment by Soulfilip-UD** [comment]
Perfecta Documentación, buena esa !!
Tarea finalizada.
Proceeding to close Issue
