### ISSUE TITLE
Ajustar modelo de movimientos para que soporte movimientos que involucran más de una entidad

### ISSUE THREAD

**Issue by juancsr** [udistrital/movimientos_crud#13]
Al comenzar el desarrollo con el movimiento de tipo traslado para las fuentes de financiamiento, se pudo evidenciar que el modelo propuesto para movimientos no era capaz de soportar un movimiento que involucre más de dos entidades, en el caso de traslado, es cuando se envía el valor de una fuente de financiamiento a otra. Por este caso es necesario ajustarlo.

**Comment by CarlosGutierrezArdila** [comment]
Se subió el modelo actualizado al [Archivo del repositorio de documentación](https://github.com/udistrital/Financiera_documentacion/blob/master/movimientos/movimientos/modelo_datos.md)

**Comment by Soulfilip-UD** [comment]
Modelo actualizado, Tarea realizada

Proceeding to close Issue 👾
