### ISSUE TITLE
Agregar sentencias manualmente para los archivos de migracion a movimientos_crud

### ISSUE THREAD

**Issue by davidmm07** [udistrital/movimientos_crud#17]
- [x] Agregar sentencias manualmente para los archivos de migracion a movimientos_crud

**Comment by davidmm07** [comment]
Tarea realizada el 4 Julio, se solicita revisión a @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea fue revisada en su tiempo , hubo falta cerrarla. 
Las migraciones corren correctamente

tarea finalizada
Proceeding to close Issue 👾
