### ISSUE TITLE
Registro de movimiento de Fuentes de financiamiento Suspensión 8 horas   --- Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/movimientos_crud#24]
- [x] Establecer los parámetros del servicio
- [x] Crear el servicio

**Comment by juancsr** [comment]
Registro de movimiento Suspensión:
* **Tipo de petición**: post
* **Parámetros**: 
```json
{
	"TipoMovimiento": 5,
	"ProcesoExterno": 13,
	"MovimientoDetalle": {
		"Valor": 3000.0,
		"FechaRegistro": "2019-07-01",
		"Descripcion": "Suspensión a fuente de financiamiento X"
	}
}
```
* **Endpoint**: movimiento_proceso_externo/registrar_movimiento
* **URL**: http://localhost:8085/v1/movimiento_proceso_externo/registrar_movimiento


![imagen](https://user-images.githubusercontent.com/19156525/61186923-af3a8600-a630-11e9-8333-efaf5e2592e7.png)

**Comment by Soulfilip-UD** [comment]
Buena documentación
Proceeding to close Issue 👾
