### ISSUE TITLE
Replicar response_format al 100% en movimientos_crud- 5 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/movimientos_crud#25]
- [x] implementacion de response format en API

**Comment by miguelramirez93** [comment]
Se añaden todos los errores de autogenerados beego (https://github.com/udistrital/utils_oas/commit/08631136c6c857cbcd8c8cfb4d5899d0944fb3ce)

**Comment by miguelramirez93** [comment]
con la anterior modificación y como ya se encuentra implementada la libreria en el repositorio no es necesario mas modificaciones mas que actualizar la libreria en la ejecución del API con go get -v ./...

**Comment by Soulfilip-UD** [comment]
Genial , perfecto!

Proceeding to close Issue :space_invader:
