### ISSUE TITLE
Extender el modelo de datos para implementar consecutivos 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/movimientos_crud#33]
- [x] plantear modelo de datos consecutivos
- 4 horas - Miguel y Carlos

**Comment by CarlosGutierrezArdila** [comment]
Junto con @miguelramirez93 se plantea la siguiente propuesta de modelo para movimientos, se espera la revision con arquitecto y DBA para implementar los servicios
![image](https://user-images.githubusercontent.com/32855979/65709109-abc27280-e055-11e9-8665-fe3eb939d0d1.png)
estado 90%

**Comment by miguelramirez93** [comment]
La idea del modelo es garantizar , en primera medida, la separación de tipos de movimientos por "name space" para que a la hora de mostrar los tipos de movimiento solo se muestren los que competen a cada sub sistema. Se define una tabla de consecutvos con el fin de controlar su acceso a nivel de API

**Comment by Soulfilip-UD** [comment]
Modelo de datos revisado, la próxima tarea es socializarlo con los arquitectos y dba para aprobación .

Tarea finalizada 👾
