### ISSUE TITLE
Documentar Readme de movimientos_crud

### ISSUE THREAD

**Issue by davidmm07** [udistrital/movimientos_crud#6]
- [x] Documentar Readme para repositorio de movimientos_crud

**Comment by Soulfilip-UD** [comment]
Asociar PR correspondiente

**Comment by davidmm07** [comment]
Se referencia a pull request en la anterior historia

**Comment by Soulfilip-UD** [comment]
Tarea completa.
Proceeding to close Issue :space_invader:
