### ISSUE TITLE
Registro de movimiento de Fuentes de financiamiento Reducción en movimientos_crud 5 horas - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/movimientos_crud#9]
Registrar el movimiento 
**Reducción**
De las fuentes de financiamiento 
- [x] Validar que el modelo soporte el registro de movimiento
- [x] Crear archivo de migración para la creación del tipo de movimiento reducción
- [x] Establecer parámetros que se envían en el endpoint para el registro

**Comment by juancsr** [comment]
Aquí un ejemplo, con registros que el modelo es capaz de soportar los datos del movimiento.

* Lo que está dentro del cuadro azul es el modelo de movimientos.
*  Lo que está dentro del cuadro verde es una representación del modelo de fuentes, que para el modelo de movimientos este ultimo se representa como un proceso externo.

![Prueba_movimiento_reduccion_fuente_financiamiento](https://user-images.githubusercontent.com/19156525/60480333-d8c9d980-9c4e-11e9-8b5a-4416ca661e86.png)

**Comment by juancsr** [comment]
egistro de movimiento adición:
* **Tipo de petición**: post
* **Parámetros**: 
```json
{
	"TipoMovimiento": 2,
	"ProcesoExterno": 1,
	"MovimientoDetalle": {
		"Valor": 700000.0,
		"FechaRegistro": "2019-07-01",
		"Descripcion": "Adición a fuente de financiamiento X"
	}
}
```
* **Endpoint**: movimiento_proceso_externo/registrar_movimiento
* **URL**: http://localhost:8085/v1/movimiento_proceso_externo/registrar_movimiento

![registro_reduccion](https://user-images.githubusercontent.com/19156525/60480885-e2544100-9c50-11e9-91d5-e1ce019fc0c3.png)

**Comment by juancsr** [comment]
El merge para la funcionalidad es el #14 puesto que los dos son movimientos

**Comment by Soulfilip-UD** [comment]
Perfecta Documentación, buena esa !!
Tarea finalizada.
Proceeding to close Issue :space_invader:
